#include<iostream>
using namespace std;

	string products, brands;
	int num, quantities, prices, stocks, solds;
void input (){
	cout<<"Enter the number of Products for Inventory: ";
	cin>> num;
	cout<<"\nEnter " <<num<< " Products";
	for (int i=1; i<=num; i++){
		cout<<"\nProduct "<< i<< " : ";
		cin>>products
	    cout<<"How many " <<products<<"? ";
	    cin>> quantities;
	    for(int j=1; j<=quantities; j++){
	    cout<<"\n"<<products<< " " << j<<" : ";
	    cin>>brands;
	    cout<<"Price: ";
	    cin>> prices;
	    cout<< "Stock: ";
	    cin>>stocks;
	    cout<< "Sold: ";
	    cin>>solds;
	}	
}
}
void displaylist(){
  cout << "\nInventory Table:\n";
    cout << "Product\tBrand\tPrice\tStock\tSold\n";
    int totalInventoryPrice = 0;
    for (int i=1; i<=num; i++) {
        for(int j=1; j<=quantities; j++) {
            cout<< products[i]<< "\t" <<brands[i][j]<< "\t" <<prices[i][j]<< "\t" <<stocks[i][j]<< "\t" <<solds[i][j]<< endl;
            totalInventoryPrice += prices[i][j] * stocks[i][j];
        }
    }
    cout << "\nTotal Inventory Price: " << totalInventoryPrice << endl;
}

int main(){
	cout<<"INVENTORY SALES SYSTEM - GROUP 3" <<endl;
	input();
	displaylist();
}

